server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true  # permite acessar com letras minúsculas
      routes:
        - id: ms1-route
          uri: lb://ms1
          predicates:
            - Path=/ms1/**
          filters:
            - StripPrefix=1

        - id: ms2-route
          uri: lb://ms2
          predicates:
            - Path=/ms2/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
